# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14bbafb724ea3be0ef7f57805fb8276dccabc10fb20af6190a458dc1e14901eaa9cb92f9ec9ca1f470d592d7a1b317608842877b91e28f203c52a2ccbd595d2

test:
  secret_key_base: a6eb994a370c12371a3e1d1b31dbc070d19a786cfa1bc29692df221a9e93e3e585a93495cf0dde365b414774c3a6781bba6a07c8266d9dfce124b7fe283d8dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
